---
- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: True
  vars:
    # Variables 'resgrp' and 'location' need to be provided at command line with arg --extra-vars
    var_env: "PROD"
    #var_env: "DEV"
    #var_env: "QA" 
    templateLink1: 'https://raw.githubusercontent.com/medhanoo/azr-arm/master/azuredeploysql.json'
    var_zipUrl: "https://connectorprod.blob.core.windows.net/bot-packages/csharp-abs-webapp_qnabot_precompiled.zip"
    #var_botId: "EYchatbot"
    var_location: "westus"
    var_kind: "sdk"
    var_sku: "F0"
    #var_siteName: "EYchatbot"
    #var_appId: "cd3b2269-5e08-4afe-bdbc-ea83703c7b3b"
    var_appSecret: "vC/FoAE@9rqCvH|l"
    var_createNewStorage: true
    #var_storageAccountName: "EYchatbotad0f"
    var_storageAccountResourceId: ""
    var_useAppInsights: true
    var_appInsightsLocation: "East US"
    var_createServerFarm: true
    var_serverFarmId: "/subscriptions/803fe6a8-c026-48c3-86f3-5d8036e3461c/resourceGroups/WEUSPRODRSGC001/providers/Microsoft.Web/serverfarms/newappplan"
    var_serverFarmLocation: "West US"
    var_azureWebJobsBotFrameworkDirectLineSecret: ""
    #var_name: "EYqna"
    #var_appName: "EYqnaq"
    var_location2: "East US"
    var_location3: "Central US"
    var_location4: "West US"
    var_sku2: "free"
    var_searchHostingMode: "default"
    var_administratorLogin: "eyadmin"
    var_administratorLoginPassword: "Password12345!"
    #var_collation: "SQL_Latin1_General_CP1_CI_AS"
    var_databaseName: "Eydbsdfsf"
    var_tier: "standard"
    var_skuName: "S0"
    var_maxSizeBytes: 268435456000
    var_sampleName: ""
    var_serverName: "eydbedf"
    var_zoneRedundant: false
    var_licenseType: ""
    var_enableATP: false
    var_allowAzureIps: true
    Var_NamesDictionary:
        Roles:
          Bot: "CHATBOT"
          StorageAccount: "BOTSTC"
          ResourceGroup: "RSGC"
          SqlServer: "SQLC"
          WebApp: "WAC"
          QNAmaker: "QNAC"
          QNAApp: "QNAAC"
          Collation: "DBCC"
          SqlDB: "DBC"
          Cache: "CHC"
        Locations:
          westus: "WEUS"
          eastus: "EUS"   
  tasks:
  - name: Creating SQL server
    azure_rm_deployment:
        state: present
        resource_group_name: 'dj-01'
        parameters:
          administratorLogin: 
            value: 'mcse123'
          administratorLoginPassword: 
            value: 'MC-se-00'
          collation: 
            value: 'abcdefg'
          databaseName: 
            value: 'test'
          tier: 
            value: 'standard'
          skuName: 
            value: 'S0'
          location: 
            value: 'West Europe'
          maxSizeBytes: 
            value: '{{ var_maxSizeBytes }}'
          serverName: 
            value: 'cccccc'
          sampleName: 
            value: ''
          zoneRedundant: 
            value: false
          licenseType: 
            value: ''
          enableATP:
            value: false
          allowAzureIps: 
            value: True
        template_link: '{{ templateLink1 }}'
        
